## 本文件含中文，使用UTF8编码保存

dbserver:
  datasource: /var/lib/my.db3

modules:
  gin:
    enable: true
    port: 9000
    website: data/dist  # html纯静态页面
  tcpserver:
    enable: false
    port: 9001

vendors:
  - foo
  - bar
  - hello

setting:
  data_file: data # 数据文件所在目录

https:
  enable: false
  cert_file: "latelee.crt"
  key_file: "latelee.key"