typemeta:
  kind: myKind
  apiversion: config.test.io/v1alpha1
database:
  drivername: sqlite3
  aliasname: default
  datasource: /var/lib/my.db
modules:
  gin:
    enable: true
    port: 8080
  tcpserver:
    enable: true
    port: 8081
